# Generated by Django 2.2.1 on 2019-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_auto_20190525_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
