# Generated by Django 2.2.1 on 2019-05-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_auto_20190526_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='admin_app/static/images/moi.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(choices=[('Immobilier', (('electromenager', 'Electromenager'), ('maison', 'Maison'), ('mobilier', 'Mobilier'), ('vaisselle', 'Vaisselle'))), ('Multimedia', (('ordinateur', 'Ordinateur'), ('telephone', 'Telephone'), ('jeux', 'Jeux Videos'), ('television', 'Television'))), ('Alimentation', (('animal', 'Animal'), ('conserve', 'Conserve'), ('fruits', 'Fruits'), ('legumes', 'Legumes'))), ('Vehicule', (('voiture', 'Voiture'), ('moto', 'Moto'), ('scooter', 'Scooter'), ('velo', 'Velo')))], default='Categorie', max_length=100),
        ),
    ]
